# All datasets and their paths relative to gtsam/examples/Data
dataset:
    CAB1: 
        is3D:           true
        path:           "ra_datasets/CAB_query_val_phone"
        relin_thresh:   0.01
        start_step:     2
        end_step:       463     # Inclusive
        period:         1
    CAB1-smallnoise: 
        is3D:           true
        path:           "ra_datasets/CAB_query_val_phone-2"
        relin_thresh:   0.001
        start_step:     2
        end_step:       463     # Inclusive
        period:         1
    CAB7000: 
        is3D:           true
        path:           "ra_datasets/CAB7000"
        relin_thresh:   0.02
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
    CAB7000-smallnoise: 
        is3D:           true
        path:           "ra_datasets/CAB7000-2"
        relin_thresh:   0.001
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
    CSAIL: 
        is3D:           false
        path:           "ra_datasets/CSAIL"
        relin_thresh:   0.01
        start_step:     2
        end_step:       1045    # Inclusive
        period:         25
        noise_format:   "graph"
    sphere2500: 
        is3D:           true
        path:           "sphere2500"
        relin_thresh:   0.05
        start_step:     2
        end_step:       2499    # Inclusive
        period:         25
    sphere2: 
        is3D:           true
        path:           "ra_datasets/sphere_smallnoise_pruned"
        relin_thresh:   0.01
        start_step:     2
        end_step:       2000    # Inclusive
        period:         25
    w10000: 
        is3D:           false
        path:           "w10000"
        relin_thresh:   0.1
        start_step:     2
        end_step:       10000   # Inclusive
        period:         1
    M3500: 
        is3D:           false
        path:           "ra_datasets/M3500"
        relin_thresh:   0.1
        start_step:     2
        end_step:       3500    # Inclusive
        period:         1
    M3500c: 
        is3D:           false
        path:           "ra_datasets/M3500c"
        relin_thresh:   0.1
        start_step:     2
        end_step:       3500    # Inclusive
        period:         1
    torus: 
        is3D:           true
        path:           "ra_datasets/torus3D"
        relin_thresh:   0.1
        start_step:     2
        end_step:       4999    # Inclusive
        period:         25

# Metadata
metadata:
    scriptdir: "."
    builddir: "../../build"
    headerdir: "../baremetal_tests"
    recompile: true     # True if C++ sources changed
    make_flags: "-j4"
    target_binary:
        - testGtsamIncremental
        - testGtsamIncremental3D
        - testGtsamIncremental-ra
        - testGtsamIncremental3D-ra
        - testGtsamIncremental-vio
        - testGtsamIncremental3D-vio
        - testGtsamIncremental-treegen
        - testGtsamIncremental3D-treegen
        - testGtsamIncremental-datasetgen
        - testGtsamIncremental3D-datasetgen
        - testGtsamIncremental3D-lru

# Resource aware
RA:
    # Runs that share the same output_format will use the same dataset run
    output_format: "RA_{dataset}_{'num_threads-{}'.format(num_threads) if not num_threads_file else 'var-threads'}"
    header_format: "RA_{dataset}_{'num_threads-{}'.format(num_threads) if not num_threads_file else 'var-threads'}_steps-{start_step}-{end_step}_period-{period}"
    dataset:    # Comment out the datasets that will be skipped
    # - CAB1
    # - CAB1-smallnoise
    # - CAB7000
    # - CAB7000-smallnoise
    # - CSAIL
    # - sphere2500
    # - sphere2
    # - w10000
    # - M3500
    # - M3500c
    params:
        num_threads:        4
        num_threads_file:   ""              # Specify the path to a num threads file or leave empty
        print_dataset:      false            # Turn this off if not generating header
        print_values:       false
        print_pred:         false
        print_traj:         true
        
# Incremental:
Incremental:
    output_format: "incremental_{dataset}"
    header_format: "incremental_{dataset}_steps-{start_step}-{end_step}_period-{period}"
    dataset:    # Comment out the datasets that will be skipped
    # - CAB1
    # - CAB1-smallnoise
    # - CAB7000
    # - CAB7000-smallnoise
    # - sphere2500
    # - sphere2
    # - w10000
    # - M3500
    # - M3500c
    - torus
    params:
        print_dataset:      true            # Turn this off if not generating header
        print_values:       false
        print_pred:         true
        print_traj:         true
        
# LRU:
LRU:
    # Runs that share the same output_format will use the same dataset run
    output_format: "LRU_{dataset}_{'num_threads-{}'.format(num_threads) if not num_threads_file else 'var-threads'}_memsize-{memsize}"
    header_format: "LRU_{dataset}_{'num_threads-{}'.format(num_threads) if not num_threads_file else 'var-threads'}_memsize-{memsize}_steps-{start_step}-{end_step}_period-{period}"
    dataset:    # Comment out the datasets that will be skipped
    # - CAB1
    # - CAB1-smallnoise
    # - CAB7000
    # - CAB7000-smallnoise
    # - sphere2500
    # - w10000
    # - M3500
    # - M3500c
    params:
        num_threads:        2
        num_threads_file:   ""              # Specify the path to a num threads file or leave empty
        memsize:            2M              # In bytes.
        print_dataset:      false            # Turn this off if not generating header
        print_values:       false
        print_pred:         false
        print_traj:         true
        gen_header:         false
        
# LC:
LC:
    output_format: "LC_{dataset}"
    header_format: "LC_{dataset}_steps-{start_step}-{end_step}_period-{period}"
    dataset:    # Comment out the datasets that will be skipped
    # - CAB1
    # - CAB1-smallnoise
    # - CAB7000
    # - CAB7000-smallnoise
    # - CSAIL
    # - sphere2500
    # - sphere2
    # - w10000
    # - M3500
    # - M3500c
    params:
        max_iter:           5
        print_dataset:      false            # Turn this off if not generating header
        print_values:       false
        print_pred:         false
        print_traj:         true
        gen_header:         false
      
# VIO:
VIO:
    output_format: "VIO{'LC' if run_lc else ''}_{dataset}_vio_lag-{vio_lag}{'_lc_period-{}'.format(lc_period) if run_lc else ''}"
    header_format: "VIO{'LC' if run_lc else ''}_{dataset}_vio_lag-{vio_lag}_steps-{start_step}-{end_step}_period-{period}"
    dataset:    # Comment out the datasets that will be skipped
    # - CAB1
    # - CAB1-smallnoise
    # - CAB7000
    # - CAB7000-smallnoise
    # - CSAIL
    # - sphere2500
    # - sphere2
    # - w10000
    # - M3500
    # - M3500c
    params:
        max_iter:           1
        gen_header:         false
        vio_lag:            716
        run_lc:             false
        lc_period:          8
        
# Legacy output directors
Legacy:
    runs:
    # - seah_sphere
    # - seah_incremental_CAB7000
    # - seah_incremental_CAB464
    # - seah_incremental_CAB1_num_threads-1
    # - seah_incremental_CAB1_num_threads-2
    # - seah_incremental_CAB1_num_threads-4
    # - seah_RA_CAB7000_num_threads-1
    # - seah_RA_CAB7000_num_threads-1
    # - seah_RA_CAB7000_num_threads-2
    # - seah_RA_CAB7000_num_threads-4
    # - seah_RA_sphere_2500_num_threads-1
    # - seah_RA_sphere_2500_num_threads-2
    # - seah_RA_sphere_2500_num_threads-4
    seah_sphere:
        dataset:        sphere2500
        start_step:     2
        end_step:       2000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "incremental_sphere2500_steps-2000_period-25"
        header_dir: "incremental_sphere2500_steps-2000_period-25"
    seah_incremental_CAB1_num_threads-1:
        dataset:        CAB1
        start_step:     2
        end_step:       463    # Inclusive
        period:         1
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_CAB1_num_threads-1"
        header_dir: "RA_CAB1_num_threads-1"
    seah_incremental_CAB1_num_threads-2:
        dataset:        CAB1
        start_step:     2
        end_step:       463    # Inclusive
        period:         1
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_CAB1_num_threads-2"
        header_dir: "RA_CAB1_num_threads-2"
    seah_incremental_CAB1_num_threads-4:
        dataset:        CAB1
        start_step:     2
        end_step:       463    # Inclusive
        period:         1
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_CAB1_num_threads-4"
        header_dir: "RA_CAB1_num_threads-4"
    seah_incremental_CAB7000:
        dataset:        CAB7000
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "incremental_CAB7000"
        header_dir: "incremental_CAB7000"
    seah_incremental_CAB464:
        dataset:        CAB1
        start_step:     2
        end_step:       463    # Inclusive
        period:         1
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "incremental_CAB1_steps-464_period-1"
        header_dir: "incremental_CAB1_steps-464_period-1"
    seah_RA_CAB7000_num_threads-1:
        dataset:        CAB7000
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_CAB7000_num_threads-1"
        header_dir: "RA_CAB7000_num_threads-1"
    seah_RA_CAB7000_num_threads-1:
        dataset:        CAB7000
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_CAB7000_num_threads-1"
        header_dir: "RA_CAB7000_num_threads-1"
    seah_RA_CAB7000_num_threads-2:
        dataset:        CAB7000
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_CAB7000_num_threads-2"
        header_dir: "RA_CAB7000_num_threads-2"
    seah_RA_CAB7000_num_threads-4:
        dataset:        CAB7000
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_CAB7000_num_threads-4"
        header_dir: "RA_CAB7000_num_threads-4"
    seah_RA_sphere_2500_num_threads-1:
        dataset:        sphere2500
        start_step:     2
        end_step:       2000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_sphere2500_num_threads-1"
        header_dir: "RA_sphere2500_num_threads-1"
    seah_RA_sphere_2500_num_threads-2:
        dataset:        sphere2500
        start_step:     2
        end_step:       2000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_sphere2500_num_threads-2"
        header_dir: "RA_sphere2500_num_threads-2"
    seah_RA_sphere_2500_num_threads-4:
        dataset:        sphere2500
        start_step:     2
        end_step:       2000    # Inclusive
        period:         25
        print_dataset:  false            # Turn this off if not generating header
        print_values:   false
        print_pred:     false
        print_traj:     false
        print_delta:    true
        output_dir: "RA_sphere2500_num_threads-4"
        header_dir: "RA_sphere2500_num_threads-4"
    
    
